apps/street_portraits_web/lib/street_portraits_web/router.ex
defmodule StreetPortraitsWeb.Router do
  use StreetPortraitsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StreetPortraitsWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/neighbors", NeighborController
    resources "/portraits", PortraitController
    resources "/outreach", OutreachController

    resources "/account_types", AccountTypeController
    resources "/access_keys", AccessKeyController
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", StreetPortraitsWeb do
  #   pipe_through :api
  # end
end

apps/street_portraits_web/lib/street_portraits_web/controllers/neighbor_controller.ex
defmodule StreetPortraitsWeb.NeighborController do
  use StreetPortraitsWeb, :controller

  alias StreetPortraits.SP
  alias StreetPortraits.SP.Neighbor

  def index(conn, _params) do
    neighbors = SP.list_neighbors()
    render(conn, "index.html", neighbors: neighbors)
  end

  def new(conn, _params) do
    changeset = SP.change_neighbor(%Neighbor{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"neighbor" => neighbor_params}) do
    case SP.create_neighbor(neighbor_params) do
      {:ok, neighbor} ->
        conn
        |> put_flash(:info, "Neighbor created successfully.")
        |> redirect(to: Routes.neighbor_path(conn, :show, neighbor))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    neighbor = SP.get_neighbor!(id)
    render(conn, "show.html", neighbor: neighbor)
  end

  def edit(conn, %{"id" => id}) do
    neighbor = SP.get_neighbor!(id)
    changeset = SP.change_neighbor(neighbor)
    render(conn, "edit.html", neighbor: neighbor, changeset: changeset)
  end

  def update(conn, %{"id" => id, "neighbor" => neighbor_params}) do
    neighbor = SP.get_neighbor!(id)

    case SP.update_neighbor(neighbor, neighbor_params) do
      {:ok, neighbor} ->
        conn
        |> put_flash(:info, "Neighbor updated successfully.")
        |> redirect(to: Routes.neighbor_path(conn, :show, neighbor))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", neighbor: neighbor, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    neighbor = SP.get_neighbor!(id)
    {:ok, _neighbor} = SP.delete_neighbor(neighbor)

    conn
    |> put_flash(:info, "Neighbor deleted successfully.")
    |> redirect(to: Routes.neighbor_path(conn, :index))
  end
end

apps/street_portraits_web/lib/street_portraits_web/views/neighbor_view.ex
defmodule StreetPortraitsWeb.NeighborView do
  use StreetPortraitsWeb, :view
end

apps/street_portraits_web/lib/street_portraits_web/templates/neighbor/edit.html.eex
<h1>Edit Neighbor</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.neighbor_path(@conn, :update, @neighbor)) %>

<span><%= link "Back", to: Routes.neighbor_path(@conn, :index) %></span>

apps/street_portraits_web/lib/street_portraits_web/templates/neighbor/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :approx_location %>
  <%= text_input f, :approx_location %>
  <%= error_tag f, :approx_location %>

  <%= label f, :phone %>
  <%= text_input f, :phone %>
  <%= error_tag f, :phone %>

  <%= label f, :address %>
  <%= text_input f, :address %>
  <%= error_tag f, :address %>

  <%= label f, :preferred_channel %>
  <%= text_input f, :preferred_channel %>
  <%= error_tag f, :preferred_channel %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

apps/street_portraits_web/lib/street_portraits_web/templates/neighbor/index.html.eex
<h1>Listing Neighbors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Approx location</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Preferred channel</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for neighbor <- @neighbors do %>
    <tr>
      <td><%= neighbor.name %></td>
      <td><%= neighbor.approx_location %></td>
      <td><%= neighbor.phone %></td>
      <td><%= neighbor.address %></td>
      <td><%= neighbor.preferred_channel %></td>

      <td>
        <%= link "Show", to: Routes.neighbor_path(@conn, :show, neighbor) %>
        <%= link "Edit", to: Routes.neighbor_path(@conn, :edit, neighbor) %>
        <%= link "Delete", to: Routes.neighbor_path(@conn, :delete, neighbor), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Neighbor", to: Routes.neighbor_path(@conn, :new) %></span>

apps/street_portraits_web/lib/street_portraits_web/templates/neighbor/new.html.eex
<h1>New Neighbor</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.neighbor_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.neighbor_path(@conn, :index) %></span>

apps/street_portraits_web/lib/street_portraits_web/templates/neighbor/show.html.eex
<h1>Show Neighbor</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @neighbor.name %>
  </li>

  <li>
    <strong>Approx location:</strong>
    <%= @neighbor.approx_location %>
  </li>

  <li>
    <strong>Phone:</strong>
    <%= @neighbor.phone %>
  </li>

  <li>
    <strong>Address:</strong>
    <%= @neighbor.address %>
  </li>

  <li>
    <strong>Preferred channel:</strong>
    <%= @neighbor.preferred_channel %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.neighbor_path(@conn, :edit, @neighbor) %></span>
<span><%= link "Back", to: Routes.neighbor_path(@conn, :index) %></span>
<span><%= link "Reach Out", to: Routes.outreach_path(@conn, :new, %{id: @neighbor.id, name: @neighbor.name}) %></span>